package hubsoft.smartsheet.sf.automation.enums;

public enum Id{
    INPUT_SHEET,
    TEMPLATE_FOLDER,
    TIMING_WORKSPACE_MF,
    TIMING_WORKSPACE_ELEVEN,
    SHOTLIST_WORKSPACE_MF,
    SHOTLIST_WORKSPACE_ELEVEN,
    TIMING_TEMPLATE,
    SHOTLIST_TEMPLATE,
    JOB_NR_COLUMN,
    LABEL_COLUMN,
    CLIENT_COLUMN,
    PROJECT_COLUMN,
    ASP_COLUMN,
    KV_COLUMN,
    T_COLUMN,
    SL_COLUMN,
    MF_WORKSPACE,
    ELEVEN_WORKSPACE
}
