package hubsoft.smartsheet.sf.automation.enums;

public enum Id{
    TEMPLATE_FOLDER,
    TIMING_WORKSPACE_MF,
    TIMING_WORKSPACE_ELEVEN,
    SHOTLIST_WORKSPACE_MF,
    SHOTLIST_WORKSPACE_ELEVEN,
    TIMING_TEMPLATE,
    SHOTLIST_TEMPLATE,
    MF_WORKSPACE,
    ELEVEN_WORKSPACE
}
